# Generated by Django 4.0.5 on 2022-07-28 18:33

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='_email_data',
            field=encrypted_fields.fields.EncryptedEmailField(default='encrypted', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_account',
            name='email',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_email_data', hash_key='b6b7029f69d04cc11f4d22a84e80d4bcab1249dbf981c58de64a69deb46e8b06', max_length=66, null=True, unique=True),
        ),
    ]
