# Generated by Django 4.0.5 on 2022-08-01 16:29

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_account__email_data_alter_user_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='email',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_email_data', hash_key='34537a967be51e4e1334b20d8aed93fbae65dba2591792c86d54a82e37b5483e', max_length=66, null=True, unique=True),
        ),
    ]
