# Generated by Django 4.0.5 on 2022-06-21 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country_code',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('cc9a9709-d561-4b5c-8a3b-c1fd46052404'), editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('country_id', models.CharField(max_length=5)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_phone_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='country_currency',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('cc9a9709-d561-4b5c-8a3b-c1fd46052404'), editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('exchange_rate_date_updated', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.country_code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
