# Generated by Django 4.0.5 on 2022-07-05 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_country_code_uid_alter_country_currency_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_code',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8dd61413-642f-4136-9955-676b643fd30d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country_currency',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8dd61413-642f-4136-9955-676b643fd30d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
