# Generated by Django 4.0.5 on 2022-07-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_account_display_currency_preference_and_more'),
        ('common', '0002_alter_country_code_uid_alter_country_currency_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_currency',
            name='country',
        ),
        migrations.DeleteModel(
            name='country_code',
        ),
        migrations.DeleteModel(
            name='country_currency',
        ),
    ]
