# Generated by Django 4.0.5 on 2022-07-12 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_country_code_uid_alter_country_currency_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_code',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='country_currency',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
