# Generated by Django 4.0.5 on 2022-07-05 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_account_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8dd61413-642f-4136-9955-676b643fd30d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
