# Generated by Django 4.0.5 on 2022-07-16 16:02

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='phone',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=15, null=True)),
        ),
    ]
