# Generated by Django 4.0.5 on 2022-07-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_account_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='display_currency_preference',
        ),
        migrations.AlterField(
            model_name='user_account',
            name='phone_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
