branch-defaults:
  default:
    environment: django-hotels-vpc4
    group_suffix: null
environment-defaults:
  django-hotels-out-dev:
    branch: null
    repository: null
  hotel-booking-django-dev:
    branch: null
    repository: null
global:
  application_name: django-hotels
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
