# Generated by Django 4.0.5 on 2022-06-21 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='secondary_guests',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('cc9a9709-d561-4b5c-8a3b-c1fd46052404'), editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('booking_id', models.IntegerField(blank=True, null=True)),
                ('secondary_guest_title', models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('MRS', 'Mrs.')], max_length=3, null=True)),
                ('secondary_guest_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_guest_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_guest_passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_guest_passport_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.country_code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='booking_order',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('cc9a9709-d561-4b5c-8a3b-c1fd46052404'), editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('hotel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('room_type_id', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('number_of_guests_per_rooms', models.IntegerField(blank=True, null=True)),
                ('special_request', models.IntegerField(blank=True, null=True)),
                ('primary_guest_title', models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('MRS', 'Mrs.')], max_length=3, null=True)),
                ('primary_guest_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_guest_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_guest_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_guest_passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_in_sgd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('primary_guest_passport_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_guest_passport_country', to='common.country_code')),
                ('primary_guest_phone_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_guest_phone_country', to='common.country_code')),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
