# Generated by Django 4.0.5 on 2022-07-15 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_booking_payment_credit_card_details_billing_address_country_and_more'),
        ('booking', '0002_alter_booking_order_uid_alter_secondary_guests_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_order',
            name='primary_guest_passport_country',
        ),
        migrations.RemoveField(
            model_name='booking_order',
            name='primary_guest_passport_number',
        ),
        migrations.AddField(
            model_name='booking_order',
            name='booking_tnc',
            field=models.CharField(default='This is a sample booking terms and condition', max_length=1000),
        ),
        migrations.AddField(
            model_name='booking_order',
            name='hotel_tnc',
            field=models.CharField(default='This is a sample hotel terms and condition', max_length=1000),
        ),
        migrations.AddField(
            model_name='booking_order',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.user_payment_credit_card_details'),
        ),
        migrations.AlterField(
            model_name='booking_order',
            name='special_request',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='secondary_guests',
        ),
    ]
