# Generated by Django 4.0.5 on 2022-07-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_order_destination_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_order',
            name='room_breakfast_info',
            field=models.CharField(default='breakfast_info', max_length=255),
            preserve_default=False,
        ),
    ]
