# Generated by Django 4.0.5 on 2022-07-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_order_primary_guest_passport_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_order',
            name='primary_guest_phone_country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
