# Generated by Django 4.0.5 on 2022-07-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_order_primary_guest_phone_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_order',
            name='did_primary_guest_accept_tnc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking_order',
            name='primary_guest_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
