# Generated by Django 4.0.5 on 2022-07-16 15:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_payment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name_on_card', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_mode', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(999999999999999)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user_payment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(999999999999999)])),
                ('is_primary_payment_mode', models.BooleanField(blank=True, default=False, null=True)),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user_payment_credit_card_details',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name_on_card', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('card_number', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True))),
                ('expiry_date', django_cryptography.fields.encrypt(models.DateField(blank=True, null=True))),
                ('security_code', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=3, null=True))),
                ('billing_address_address', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('billing_address_city', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True))),
                ('billing_address_post_code', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True))),
                ('billing_address_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.country_code')),
                ('user_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment.user_payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='booking_payment_credit_card_details',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name_on_card', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.IntegerField(blank=True, null=True)),
                ('security_code', models.IntegerField(blank=True, null=True)),
                ('billing_address_address', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address_post_code', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.country_code')),
                ('booking_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.booking_payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
