# Generated by Django 4.0.5 on 2022-07-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_booking_payment_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_payment_credit_card_details',
            name='billing_address_country',
        ),
        migrations.RemoveField(
            model_name='booking_payment_credit_card_details',
            name='booking_payment',
        ),
        migrations.AlterField(
            model_name='user_payment_credit_card_details',
            name='billing_address_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_payment_credit_card_details',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_payment_credit_card_details',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='booking_payment',
        ),
        migrations.DeleteModel(
            name='booking_payment_credit_card_details',
        ),
    ]
