# Generated by Django 4.0.5 on 2022-08-01 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_alter_user_payment_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_payment_credit_card_details',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='user_payment_credit_card_details',
            name='security_code',
        ),
        migrations.AlterField(
            model_name='user_payment',
            name='user_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_payment_credit_card_details',
            name='user_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.user_payment'),
        ),
    ]
