# Generated by Django 4.0.5 on 2022-07-16 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_remove_booking_payment_credit_card_details_billing_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_payment',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_payment_credit_card_details',
            name='billing_address_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_payment_credit_card_details',
            name='billing_address_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_payment_credit_card_details',
            name='billing_address_country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_payment_credit_card_details',
            name='billing_address_post_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_payment_credit_card_details',
            name='card_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_payment_credit_card_details',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_payment_credit_card_details',
            name='name_on_card',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_payment_credit_card_details',
            name='security_code',
            field=models.IntegerField(),
        ),
    ]
